name: CI

on:
  push:
    branches: [ sp-json ]
  pull_request:
    branches: [ sp-json ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sm_version: ['1.9.x', '1.10.x', '1.11.x']

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      
      - name: Checkout sm-json
        uses: actions/checkout@v2
        with:
          repository: clugg/sm-json
          ref: 3a9e22b8b4056809c95b3329e9f779b9c0be34cc
          path: sm_json
        
      - name: Checkout SteamWorks
        uses: actions/checkout@v2
        with:
          repository: KyleSanderson/SteamWorks
          ref: ef731826ddf504d2d8caaa5fcde4c6a7045de6fa
          path: SteamWorks

      - name: Setup SourcePawn Compiler
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.sm_version }}

      - name: Create directory
        run: mkdir -p compiled
        
      - name: Copy dependencies
        run: |
          cp sm_json/addons/sourcemod/scripting/include/json.inc include/
          cp -r sm_json/addons/sourcemod/scripting/include/json include/json/
          cp SteamWorks/Pawn/includes/SteamWorks.inc include/
      
      - name: Compile Plugins
        run: |
          spcomp -i include discord_api.sp -o compiled/discord_api.smx
          spcomp -i include discord_test.sp -o compiled/discord_test.smx

      - name: Upload plugin artifact
        uses: actions/upload-artifact@master
        with:
          name: Plugins
          path: compiled/
