name: CI

on:
  push:
    branches: [ sp-json ]
  pull_request:
    branches: [ sp-json ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sm_version: ['1.9.x', '1.10.x', '1.11.x']

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      
      - name: Checkout sm-json
        uses: actions/checkout@v2
        with:
          repository: https://github.com/clugg/sm-json/tree/v3.1.0
          path: sm-json
        
      - name: Checkout SteamWorks
        uses: actions/checkout@v2
        with:
          repository: https://github.com/KyleSanderson/SteamWorks/tree/1.2.3c
          path: SteamWorks
      
      - name: Copy dependencies
        run: |
          cp sm-json/addons/sourcemod/scripting/json.inc include/json.inc
          cp sm-json/addons/sourcemod/scripting/json include/json
          cp SteamWorks/Pawn/includes/SteamWorks.inc include/SteamWorks.inc

      - name: Setup SourcePawn Compiler
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.sm_version }}

      - name: Create directory
        run: mkdir -p compiled
        
      - name: Compile Plugins
        run: |
          spcomp -i include discord_api.sp -o compiled/discord_api.smx
          spcomp -i include discord_test.sp -o compiled/discord_test.smx

      - name: Upload plugin artifact
        uses: actions/upload-artifact@master
        with:
          name: Plugins
          path: compiled/
